---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 张永钦.
--- DateTime: 2022/11/17 10:54
---
-- 比较线程标示与锁中的标示是否一致
if(redis.call('get', KEYS[1]) ==  ARGV[1]) then
    -- 释放锁 del key
    return redis.call('del', KEYS[1])
end
return 0